#set page(paper: "us-letter", margin: (x: 1.5cm, top: 1.5cm, bottom: 1.7cm),
  footer: context [
    #set text(size: 7.5pt, fill: luma(55%))
    #line(length: 100%, stroke: 0.5pt + luma(78%))
    #v(2pt)
    #grid(columns: (1fr, auto),
      [Generated by netimpact 0.1.0 · 2026-08-17],
      [#counter(page).display() / #counter(page).final().first()])
  ])
#set text(font: ("Helvetica Neue", "Arial"), size: 10pt, number-width: "tabular")
#let teal = rgb("#235a68")
#let sparkbar(p) = box(width: 90%, height: 0.32em,
  fill: luma(90%))[#box(width: p * 1%, height: 100%, fill: teal)]
#let seclabel(t) = [#v(12pt)#text(size: 7.5pt, fill: luma(45%), tracking: 0.8pt)[#upper(t)]#v(2pt)]
#let colhead(t) = text(size: 7.5pt, fill: luma(45%), tracking: 0.5pt)[#upper(t)]
#let bignum(t) = text(fill: teal, weight: "bold", size: 12pt)[#t]

#grid(columns: (1fr, auto), align: (left + bottom, right + bottom), column-gutter: 12pt,
  text(size: 18pt, weight: "bold")[Network Impact Report — Posit Assistant Workshop],
  text(size: 9.5pt, fill: luma(40%))[2026-08-17 · 20 students · 6-hour session \
    #text(weight: 800, tracking: 1pt,
      fill: rgb("#c2762c"))[MODERATE]],
)
#v(5pt)
#line(length: 100%, stroke: 1pt)

#v(10pt)
#line(length: 100%, stroke: 0.6pt + luma(55%))
#table(columns: (1fr, 1fr, 1fr, 1fr, 1fr), stroke: none, inset: (x: 10pt, y: 8pt),
  table.vline(x: 1, stroke: 0.3pt + luma(88%)), table.vline(x: 2, stroke: 0.3pt + luma(88%)),
  table.vline(x: 3, stroke: 0.3pt + luma(88%)), table.vline(x: 4, stroke: 0.3pt + luma(88%)),
  [#bignum[33.66 GB] \ #text(size: 7.5pt, fill: luma(45%), tracking: 0.8pt)[#upper[One-time downloads]]],
  [#bignum[1.68 GB] \ #text(size: 7.5pt, fill: luma(45%), tracking: 0.8pt)[#upper[Avg per student]]],
  [#bignum[385.78 MB] \ #text(size: 7.5pt, fill: luma(45%), tracking: 0.8pt)[#upper[Assistant, whole room]]],
  [#bignum[0.143 Mbps] \ #text(size: 7.5pt, fill: luma(45%), tracking: 0.8pt)[#upper[Assistant room average]]],
  [#bignum[0.39 Mbps] \ #text(size: 7.5pt, fill: luma(45%), tracking: 0.8pt)[#upper[All streams at once]]],
)
#line(length: 100%, stroke: 0.6pt + luma(55%))

#seclabel[Venue impact]
#text(size: 10.5pt)[AI assistant traffic is negligible: 385.78 MB for the whole room over the full session, averaging 0.143 Mbps — less than one video call. Plan around the one-time 33.66 GB download burst: stagger the install step or ask attendees to install before arriving.]

#seclabel[Installers — 31.28 GB total]
#table(columns: (1fr, auto, auto, auto, 88pt), stroke: none, inset: (x: 8pt, y: 7pt),
  align: (left + horizon, right + horizon, right + horizon, right + horizon, left + horizon),
  table.header(colhead[Item], colhead[Size], colhead[Students], colhead[Aggregate], []),
  table.hline(stroke: 0.6pt + luma(55%)),
  [#text(weight: 500)[Python (macOS)] \ #text(size: 7.5pt, fill: luma(50%))[python-3.14.7-macos11.pkg]], [78.56 MB], [10], [#bignum[785.58 MB]], [#sparkbar(27.4)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[Python (Windows)] \ #text(size: 7.5pt, fill: luma(50%))[python-3.14.7-amd64.exe]], [33.26 MB], [10], [#bignum[332.58 MB]], [#sparkbar(17.8)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[R (macOS)] \ #text(size: 7.5pt, fill: luma(50%))[R-4.6.1-arm64.pkg]], [105.07 MB], [10], [#bignum[1.05 GB]], [#sparkbar(31.7)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[R (Windows)] \ #text(size: 7.5pt, fill: luma(50%))[R-4.6.1-win.exe]], [91.75 MB], [10], [#bignum[917.50 MB]], [#sparkbar(29.6)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[Positron (macOS)] \ #text(size: 7.5pt, fill: luma(50%))[Positron-2026.08.1-2-arm64.dmg]], [1.05 GB], [10], [#bignum[10.45 GB]], [#sparkbar(100.0)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[Positron (Windows)] \ #text(size: 7.5pt, fill: luma(50%))[Positron-2026.08.1-2-UserSetup-x64.exe]], [522.83 MB], [10], [#bignum[5.23 GB]], [#sparkbar(70.7)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[RStudio Desktop (macOS)] \ #text(size: 7.5pt, fill: luma(50%))[RStudio-2026.08.0-187.dmg]], [852.53 MB], [10], [#bignum[8.53 GB]], [#sparkbar(90.3)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[RStudio Desktop (Windows)] \ #text(size: 7.5pt, fill: luma(50%))[RStudio-2026.08.0-187.exe]], [399.46 MB], [10], [#bignum[3.99 GB]], [#sparkbar(61.8)],
  table.hline(stroke: 0.3pt + luma(88%)),
)

#seclabel[Workshop packages — 2.37 GB total]
#table(columns: (1fr, auto, auto, auto, 88pt), stroke: none, inset: (x: 8pt, y: 7pt),
  align: (left + horizon, right + horizon, right + horizon, right + horizon, left + horizon),
  table.header(colhead[Item], colhead[Size], colhead[Students], colhead[Aggregate], []),
  table.hline(stroke: 0.6pt + luma(55%)),
  [#text(weight: 500)[Python packages: querychat + shinychat] \ #text(size: 7.5pt, fill: luma(50%))[71 packages resolved from querychat, shinychat]], [67.81 MB], [20], [#bignum[1.36 GB]], [#sparkbar(36.0)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[R packages: querychat + shinychat] \ #text(size: 7.5pt, fill: luma(50%))[48 packages resolved from querychat, shinychat]], [50.73 MB], [20], [#bignum[1.01 GB]], [#sparkbar(31.2)],
  table.hline(stroke: 0.3pt + luma(88%)),
)
#seclabel[AI assistant traffic]
#table(columns: (1fr, auto, auto, auto, auto), stroke: none, inset: (x: 8pt, y: 7pt),
  align: (left + horizon, right + horizon, right + horizon, right + horizon, right + horizon),
  table.header(colhead[Activity], colhead[Convs/student], colhead[Per conversation],
    colhead[Per student], colhead[Room total]),
  table.hline(stroke: 0.6pt + luma(55%)),
  [#text(weight: 500)[First conversation with Posit Assistant]], [1], [2.68 MB], [2.68 MB], [#bignum[53.57 MB]],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[querychat exercises (natural-language data queries)]], [2], [321.84 KB], [643.68 KB], [#bignum[12.87 MB]],
  table.hline(stroke: 0.3pt + luma(88%)),
  [#text(weight: 500)[General assistant use (debugging, plots, dashboards)]], [4], [3.99 MB], [15.97 MB], [#bignum[319.33 MB]],
  table.hline(stroke: 0.3pt + luma(88%)),
)
#v(3pt)
#text(size: 9pt, fill: luma(35%))[Whole room, whole session: 385.78 MB — an average of 0.143 Mbps. If every student's assistant streamed a response at the same instant: about 0.39 Mbps, less than one video call.]

#seclabel[Worst case — every student downloads everything at the venue, at once]
#table(columns: (auto, auto, 120pt), stroke: none, inset: (x: 8pt, y: 7pt),
  align: (left + horizon, right + horizon, left + horizon),
  table.header(colhead[Venue link], colhead[All downloads complete in], []),
  table.hline(stroke: 0.6pt + luma(55%)),
  [50 Mbps], [#bignum[128.2 min]], [#sparkbar(100.0)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [100 Mbps], [#bignum[64.1 min]], [#sparkbar(70.7)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [250 Mbps], [#bignum[25.6 min]], [#sparkbar(44.7)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [500 Mbps], [#bignum[12.8 min]], [#sparkbar(31.6)],
  table.hline(stroke: 0.3pt + luma(88%)),
  [1000 Mbps], [#bignum[6.4 min]], [#sparkbar(22.3)],
  table.hline(stroke: 0.3pt + luma(88%)),
)
#v(3pt)
#text(size: 9pt, fill: luma(35%))[Assumes shared Wi-Fi delivers about 70% of the
advertised link speed to actual downloads. Staggering the install step or asking attendees to
install before arriving removes this burst entirely.]

#seclabel[Assumptions]
#text(size: 8.5pt, fill: luma(35%))[
  Download sizes are measured live from the release CDNs and package indexes (largest platform
  wheel per package, conservative). Assistant traffic is modeled: 4
  bytes per request token, 30 bytes per streamed token including
  SSE framing, 1.08× TLS/HTTP overhead, responses streaming at
  75 tokens/second. Chat APIs are stateless — each round trip
  re-sends the conversation so far, which the model accounts for; provider-side prompt caching
  reduces cost and latency but not network transfer. Full model description and grounding:
  github.com/statik/measuring-agent-bandwidth (METHODOLOGY.md).
]
