"""Render report data as a Typst document, a PDF, or an HTML preview.

The layout: white US Letter page, Helvetica, bold title with right-aligned
metadata over a heavy rule, tracked uppercase gray section labels, tables
with hairline row separators, teal accents, and square-root-scaled sparkbars
so small values stay visible next to large ones.
"""

from __future__ import annotations

import math
import re

from netimpact.engine import format_bytes

TEAL = "#235a68"


def escape_typst(text: str) -> str:
    """Escape characters that Typst would interpret as markup."""
    return re.sub(r"([\\#$*_\[\]@~<>])", r"\\\1", text)


def _spark_percent(value: float, maximum: float) -> float:
    if maximum <= 0 or value <= 0:
        return 0.0
    return round(math.sqrt(value / maximum) * 100, 1)


def _typst_preamble(results: dict) -> str:
    generated = results["generated"][:10]
    return f"""\
#set page(paper: "us-letter", margin: (x: 1.5cm, top: 1.5cm, bottom: 1.7cm),
  footer: context [
    #set text(size: 7.5pt, fill: luma(55%))
    #line(length: 100%, stroke: 0.5pt + luma(78%))
    #v(2pt)
    #grid(columns: (1fr, auto),
      [Generated by {escape_typst(results["tool"])} · {generated}],
      [#counter(page).display() / #counter(page).final().first()])
  ])
#set text(font: ("Helvetica Neue", "Arial"), size: 10pt, number-width: "tabular")
#let teal = rgb("{TEAL}")
#let sparkbar(p) = box(width: 90%, height: 0.32em,
  fill: luma(90%))[#box(width: p * 1%, height: 100%, fill: teal)]
#let seclabel(t) = [#v(12pt)#text(size: 7.5pt, fill: luma(45%), tracking: 0.8pt)[#upper(t)]#v(2pt)]
#let colhead(t) = text(size: 7.5pt, fill: luma(45%), tracking: 0.5pt)[#upper(t)]
#let bignum(t) = text(fill: teal, weight: "bold", size: 12pt)[#t]
"""


def _typst_title(results: dict) -> str:
    workshop = results["workshop"]
    verdict = results["verdict"]
    meta = (
        f"{results['generated'][:10]} · {workshop['students']} students · "
        f"{workshop['duration_hours']:g}-hour session"
    )
    return f"""
#grid(columns: (1fr, auto), align: (left + bottom, right + bottom), column-gutter: 12pt,
  text(size: 18pt, weight: "bold")[Network Impact Report — {escape_typst(workshop["name"])}],
  text(size: 9.5pt, fill: luma(40%))[{escape_typst(meta)} \\
    #text(weight: 800, tracking: 1pt,
      fill: rgb("{verdict["color"]}"))[{escape_typst(verdict["label"])}]],
)
#v(5pt)
#line(length: 100%, stroke: 1pt)
"""


def _typst_stats(results: dict) -> str:
    one_time = results["one_time"]
    assistant = results["assistant"]
    stats = (
        (format_bytes(one_time["aggregate_bytes"]), "One-time downloads"),
        (format_bytes(one_time["average_bytes_per_student"]), "Avg per student"),
        (format_bytes(assistant["aggregate_bytes"]), "Assistant, whole room"),
        (f"{assistant['average_mbps']:g} Mbps", "Assistant room average"),
        (f"{assistant['all_streaming_at_once_mbps']:g} Mbps", "All streams at once"),
    )
    cells = ",\n  ".join(
        f"[#bignum[{escape_typst(value)}] \\ #text(size: 7.5pt, fill: luma(45%), "
        f"tracking: 0.8pt)[#upper[{escape_typst(label)}]]]"
        for value, label in stats
    )
    return f"""
#v(10pt)
#line(length: 100%, stroke: 0.6pt + luma(55%))
#table(columns: (1fr, 1fr, 1fr, 1fr, 1fr), stroke: none, inset: (x: 10pt, y: 8pt),
  table.vline(x: 1, stroke: 0.3pt + luma(88%)), table.vline(x: 2, stroke: 0.3pt + luma(88%)),
  table.vline(x: 3, stroke: 0.3pt + luma(88%)), table.vline(x: 4, stroke: 0.3pt + luma(88%)),
  {cells},
)
#line(length: 100%, stroke: 0.6pt + luma(55%))

#seclabel[Venue impact]
#text(size: 10.5pt)[{escape_typst(results["verdict"]["impact"])}]
"""


def _typst_downloads(results: dict) -> str:
    groups = results["one_time"]["groups"]
    if not groups:
        return "\n#seclabel[One-time downloads]\nNone — nothing is downloaded at the venue.\n"
    maximum = max(row["aggregate_bytes"] for g in groups for row in g["items"])
    parts = []
    for group in groups:
        rows = []
        for row in group["items"]:
            name = escape_typst(row["name"])
            detail = escape_typst(row["detail"])
            rows.append(
                f"[#text(weight: 500)[{name}] \\ #text(size: 7.5pt, fill: luma(50%))[{detail}]], "
                f"[{format_bytes(row['bytes_each'])}], [{row['downloads']:g}], "
                f"[#bignum[{format_bytes(row['aggregate_bytes'])}]], "
                f"[#sparkbar({_spark_percent(row['aggregate_bytes'], maximum)})],\n"
                "  table.hline(stroke: 0.3pt + luma(88%)),"
            )
        joined = "\n  ".join(rows)
        parts.append(f"""
#seclabel[{escape_typst(group["group"])} — {format_bytes(group["aggregate_bytes"])} total]
#table(columns: (1fr, auto, auto, auto, 88pt), stroke: none, inset: (x: 8pt, y: 7pt),
  align: (left + horizon, right + horizon, right + horizon, right + horizon, left + horizon),
  table.header(colhead[Item], colhead[Size], colhead[Students], colhead[Aggregate], []),
  table.hline(stroke: 0.6pt + luma(55%)),
  {joined}
)""")
    return "\n".join(parts)


def _typst_assistant(results: dict) -> str:
    assistant = results["assistant"]
    if not assistant["items"]:
        return "\n#seclabel[AI assistant traffic]\nNone modeled for this session.\n"
    rows = []
    for row in assistant["items"]:
        per_conversation = (
            row["uplink_bytes_per_conversation"] + row["downlink_bytes_per_conversation"]
        )
        rows.append(
            f"[#text(weight: 500)[{escape_typst(row['name'])}]], "
            f"[{row['conversations_per_student']}], [{format_bytes(per_conversation)}], "
            f"[{format_bytes(row['bytes_per_student'])}], "
            f"[#bignum[{format_bytes(row['aggregate_bytes'])}]],\n"
            "  table.hline(stroke: 0.3pt + luma(88%)),"
        )
    joined = "\n  ".join(rows)
    note = (
        f"Whole room, whole session: {format_bytes(assistant['aggregate_bytes'])} — an average of "
        f"{assistant['average_mbps']:g} Mbps. If every student's assistant streamed a response at "
        f"the same instant: about {assistant['all_streaming_at_once_mbps']:g} Mbps, "
        "less than one video call."
    )
    return f"""
#seclabel[AI assistant traffic]
#table(columns: (1fr, auto, auto, auto, auto), stroke: none, inset: (x: 8pt, y: 7pt),
  align: (left + horizon, right + horizon, right + horizon, right + horizon, right + horizon),
  table.header(colhead[Activity], colhead[Convs/student], colhead[Per conversation],
    colhead[Per student], colhead[Room total]),
  table.hline(stroke: 0.6pt + luma(55%)),
  {joined}
)
#v(3pt)
#text(size: 9pt, fill: luma(35%))[{escape_typst(note)}]
"""


def _typst_burst(results: dict) -> str:
    burst = results["download_burst"]
    maximum = max(row["minutes"] for row in burst) if burst else 0
    rows = []
    for row in burst:
        rows.append(
            f"[{row['link_mbps']} Mbps], [#bignum[{row['minutes']:g} min]], "
            f"[#sparkbar({_spark_percent(row['minutes'], maximum)})],\n"
            "  table.hline(stroke: 0.3pt + luma(88%)),"
        )
    joined = "\n  ".join(rows)
    goodput = int(results["assumptions"]["wifi_goodput_factor"] * 100)
    return f"""
#seclabel[Worst case — every student downloads everything at the venue, at once]
#table(columns: (auto, auto, 120pt), stroke: none, inset: (x: 8pt, y: 7pt),
  align: (left + horizon, right + horizon, left + horizon),
  table.header(colhead[Venue link], colhead[All downloads complete in], []),
  table.hline(stroke: 0.6pt + luma(55%)),
  {joined}
)
#v(3pt)
#text(size: 9pt, fill: luma(35%))[Assumes {goodput}% of link speed as real-world Wi-Fi goodput.
Staggering the install step or asking attendees to install before arriving removes this burst
entirely.]
"""


def _typst_assumptions(results: dict) -> str:
    a = results["assumptions"]
    return f"""
#seclabel[Assumptions]
#text(size: 8.5pt, fill: luma(35%))[
  Download sizes are measured live from the release CDNs and package indexes (largest platform
  wheel per package, conservative). Assistant traffic is modeled: {a["bytes_per_request_token"]:g}
  bytes per request token, {a["bytes_per_streamed_token"]:g} bytes per streamed token including
  SSE framing, {a["protocol_overhead"]:g}\u00d7 TLS/HTTP overhead, responses streaming at
  {a["stream_tokens_per_second"]} tokens/second. Chat APIs are stateless — each round trip
  re-sends the conversation so far, which the model accounts for; provider-side prompt caching
  reduces cost and latency but not network transfer.
]
"""


def typst_report(results: dict) -> str:
    """Render the aggregated results as a Typst document.

    Args:
        results: The dict produced by engine.summarize().

    Returns:
        Typst source for the report, compilable with any Typst 0.12+.
    """
    return (
        _typst_preamble(results)
        + _typst_title(results)
        + _typst_stats(results)
        + _typst_downloads(results)
        + _typst_assistant(results)
        + _typst_burst(results)
        + _typst_assumptions(results)
    )


def render_pdf(typst_source: str) -> bytes:
    """Compile Typst source to PDF bytes using the typst package.

    Args:
        typst_source: A complete Typst document.

    Returns:
        The compiled PDF.

    Raises:
        RuntimeError: If the typst package is not installed.
    """
    try:
        import typst
    except ImportError as error:
        raise RuntimeError("PDF output needs the 'typst' package: pip install typst") from error
    result = typst.compile(typst_source.encode())
    if isinstance(result, list):
        raise RuntimeError("unexpected multi-document output from typst.compile")
    return result


def _html_escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


HTML_STYLE = f"""
.ni-report {{ font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; font-size: 13px;
  color: #111; background: #fff; max-width: 760px; margin: 0 auto; padding: 36px 40px;
  font-variant-numeric: tabular-nums; border: 1px solid #e3e3e3; }}
.ni-report .titlebar {{ display: flex; justify-content: space-between;
  align-items: flex-end; gap: 16px; }}
.ni-report h1 {{ font-size: 21px; font-weight: 700; letter-spacing: -0.2px; margin: 0; }}
.ni-report .meta {{ font-size: 11.5px; color: #666; text-align: right; }}
.ni-report .verdict {{ font-weight: 800; letter-spacing: 1px; }}
.ni-report .rule {{ border: 0; border-top: 1.4px solid #111; margin: 8px 0 6px; }}
.ni-report .stats {{ display: flex; margin-top: 16px; border-top: 0.6px solid #8c8c8c;
  border-bottom: 0.6px solid #8c8c8c; }}
.ni-report .stat {{ flex: 1; padding: 10px 12px; border-right: 0.3px solid #e0e0e0; }}
.ni-report .stat:last-child {{ border-right: 0; }}
.ni-report .stat b {{ display: block; font-size: 16px; font-weight: 700; color: {TEAL}; }}
.ni-report .stat span {{ font-size: 9px; letter-spacing: 0.8px; text-transform: uppercase;
  color: #737373; }}
.ni-report .label {{ font-size: 9.5px; letter-spacing: 0.8px; text-transform: uppercase;
  color: #737373; margin: 20px 0 6px; }}
.ni-report table {{ width: 100%; border-collapse: collapse; }}
.ni-report th {{ font-size: 9.5px; font-weight: 500; letter-spacing: 0.5px;
  text-transform: uppercase;
  color: #737373; text-align: left; padding: 0 8px 5px; border-bottom: 0.6px solid #8c8c8c; }}
.ni-report td {{ padding: 9px 8px; border-bottom: 0.3px solid #e0e0e0; vertical-align: middle; }}
.ni-report td.num {{ text-align: right; white-space: nowrap; }}
.ni-report th.num {{ text-align: right; }}
.ni-report td.count {{ font-size: 14px; font-weight: 700; color: {TEAL}; text-align: right;
  white-space: nowrap; }}
.ni-report .note {{ color: #808080; font-size: 10.5px; }}
.ni-report .spark {{ width: 110px; }}
.ni-report .spark .track {{ width: 100%; height: 4px; background: #e5e5e5; }}
.ni-report .spark .fill {{ height: 100%; background: {TEAL}; }}
.ni-report .impact {{ font-size: 13.5px; color: #333; }}
.ni-report .footer {{ border-top: 0.5px solid #c7c7c7; margin-top: 26px; padding-top: 5px;
  display: flex; justify-content: space-between; font-size: 9.5px; color: #8c8c8c; }}
"""


def _html_spark(value: float, maximum: float) -> str:
    percent = _spark_percent(value, maximum)
    return (
        f'<td class="spark"><div class="track">'
        f'<div class="fill" style="width:{percent}%"></div></div></td>'
    )


def _html_downloads(results: dict) -> list[str]:
    groups = results["one_time"]["groups"]
    if not groups:
        return ['<div class="label">One-time downloads</div><div class="impact">None.</div>']
    maximum = max(row["aggregate_bytes"] for g in groups for row in g["items"])
    parts = []
    for group in groups:
        title = f"{group['group']} — {format_bytes(group['aggregate_bytes'])} total"
        parts.append(f'<div class="label">{_html_escape(title)}</div>')
        parts.append(
            '<table><tr><th>Item</th><th class="num">Size</th><th class="num">Students</th>'
            '<th class="num">Aggregate</th><th></th></tr>'
        )
        for row in group["items"]:
            parts.append(
                f"<tr><td>{_html_escape(row['name'])}<br>"
                f'<span class="note">{_html_escape(row["detail"])}</span></td>'
                f'<td class="num">{format_bytes(row["bytes_each"])}</td>'
                f'<td class="num">{row["downloads"]:g}</td>'
                f'<td class="count">{format_bytes(row["aggregate_bytes"])}</td>'
                f"{_html_spark(row['aggregate_bytes'], maximum)}</tr>"
            )
        parts.append("</table>")
    return parts


def _html_assistant(results: dict) -> list[str]:
    assistant = results["assistant"]
    parts = ['<div class="label">AI assistant traffic</div>']
    if not assistant["items"]:
        return [*parts, '<div class="impact">None modeled for this session.</div>']
    parts.append(
        '<table><tr><th>Activity</th><th class="num">Convs/student</th>'
        '<th class="num">Per conversation</th><th class="num">Per student</th>'
        '<th class="num">Room total</th></tr>'
    )
    for row in assistant["items"]:
        per_conversation = (
            row["uplink_bytes_per_conversation"] + row["downlink_bytes_per_conversation"]
        )
        parts.append(
            f"<tr><td>{_html_escape(row['name'])}</td>"
            f'<td class="num">{row["conversations_per_student"]}</td>'
            f'<td class="num">{format_bytes(per_conversation)}</td>'
            f'<td class="num">{format_bytes(row["bytes_per_student"])}</td>'
            f'<td class="count">{format_bytes(row["aggregate_bytes"])}</td></tr>'
        )
    parts.append("</table>")
    parts.append(
        f'<div class="note" style="margin-top:5px">Whole room, whole session: '
        f"{format_bytes(assistant['aggregate_bytes'])} — an average of "
        f"{assistant['average_mbps']:g} Mbps. "
        f"If every student's assistant streamed at the same instant: about "
        f"{assistant['all_streaming_at_once_mbps']:g} Mbps, less than one video call.</div>"
    )
    return parts


def _html_burst(results: dict) -> list[str]:
    burst = results["download_burst"]
    maximum = max(row["minutes"] for row in burst) if burst else 0
    goodput = int(results["assumptions"]["wifi_goodput_factor"] * 100)
    parts = [
        '<div class="label">Worst case — every student downloads everything '
        "at the venue, at once</div>",
        '<table><tr><th>Venue link</th><th class="num">All downloads complete in</th>'
        "<th></th></tr>",
    ]
    for row in burst:
        parts.append(
            f'<tr><td>{row["link_mbps"]} Mbps</td><td class="count">{row["minutes"]:g} min</td>'
            f"{_html_spark(row['minutes'], maximum)}</tr>"
        )
    parts.append("</table>")
    parts.append(
        f'<div class="note" style="margin-top:5px">Assumes {goodput}% of link speed as real-world '
        "Wi-Fi goodput. Staggering the install step or asking attendees to install before "
        "arriving removes this burst entirely.</div>"
    )
    return parts


def html_report(results: dict) -> str:
    """Render the aggregated results as a self-contained HTML fragment.

    Args:
        results: The dict produced by engine.summarize().

    Returns:
        An HTML fragment (styles included) matching the PDF layout.
    """
    workshop = results["workshop"]
    verdict = results["verdict"]
    one_time = results["one_time"]
    assistant = results["assistant"]
    meta = (
        f"{results['generated'][:10]} · {workshop['students']} students · "
        f"{workshop['duration_hours']:g}-hour session"
    )
    stats = (
        (format_bytes(one_time["aggregate_bytes"]), "One-time downloads"),
        (format_bytes(one_time["average_bytes_per_student"]), "Avg per student"),
        (format_bytes(assistant["aggregate_bytes"]), "Assistant, whole room"),
        (f"{assistant['average_mbps']:g} Mbps", "Assistant room average"),
        (f"{assistant['all_streaming_at_once_mbps']:g} Mbps", "All streams at once"),
    )
    stat_cells = "".join(
        f'<div class="stat"><b>{_html_escape(v)}</b><span>{_html_escape(label)}</span></div>'
        for v, label in stats
    )
    parts = [
        f"<style>{HTML_STYLE}</style>",
        '<div class="ni-report">',
        '<div class="titlebar">',
        f"<h1>Network Impact Report — {_html_escape(workshop['name'])}</h1>",
        f'<div class="meta">{_html_escape(meta)}<br>'
        f'<span class="verdict" style="color:{verdict["color"]}">'
        f"{_html_escape(verdict['label'])}</span></div>",
        "</div>",
        '<hr class="rule">',
        f'<div class="stats">{stat_cells}</div>',
        '<div class="label">Venue impact</div>',
        f'<div class="impact">{_html_escape(verdict["impact"])}</div>',
        *_html_downloads(results),
        *_html_assistant(results),
        *_html_burst(results),
        f'<div class="footer"><span>Generated by {_html_escape(results["tool"])} · '
        f"{results['generated'][:10]}</span><span>netimpact</span></div>",
        "</div>",
    ]
    return "\n".join(parts)
